[tool.poetry]
name = "nemseer"
version = "0.1.0"
description = "A package for downloading and handling forecasts for the National Electricity Market (NEM) from the Australian Energy Market Operator (AEMO)."
authors = ["Abhijith Prakash"]
license = "BSD 3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
attrs = "^21"
beautifulsoup4 = "^4"
nemosis = "^3"
pandas = "^1"
requests = "^2"
xarray = "^2022"

[tool.poetry.dev-dependencies]
ipdb = "*"
ipython = "*"
flake8 = "*"
mypy = "*"
pytest = "^7"
pytest-cov = "^3"
Sphinx = "^5.0.2"
furo = "^2022.6.21"
sphinx-copybutton = "^0.5.0"
sphinxcontrib-napoleon = "^0.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
