[tool.poetry]
name = "nemseer"
version = "0.1.0"
description = "A package for downloading and handling forecasts for the National Electricity Market (NEM) from the Australian Energy Market Operator (AEMO)."
authors = ["Abhijith Prakash"]
license = "BSD 3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
attrs = "^21"
beautifulsoup4 = "^4"
nemosis = "^3"
netCDF4 = "^1.6.0"
numpy = "^1.23.0"
packaging = "^21.3"
pandas = "^1"
requests = "^2"
SQLAlchemy = "^1.4.39"
xarray = "^2022"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
Sphinx = "^5.0.2"
furo = "^2022.6.21"
myst-parser = "^0.18.0"

[tool.poetry.group.debug]
optional = true

[tool.poetry.group.debug.dependencies]
ipdb = "*"
ipython = "*"
jupyter = "^1.0.0"
notebook = "^6.4.12"

[tool.poetry.group.linters]
optional = true

[tool.poetry.group.linters.dependencies]
flake8 = "*"
mypy = "*"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7"
pytest-cov = "^3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
